const API_BASE_URL_DEV = "http://localhost:6772";
const API_BASE_URL_PROD = "http://etracker.web.app";

const ENDPOINTS = {
  GET_ALL_EMPLOYEES: "admin/api/employees",
  GET_EMPLOYEE_BY_ID: "get-employee-by-id",
  CREATE_EMPLOYEE: "create-employee",
  UPDATE_EMPLOYEE: "update-employee",
  DELETE_EMPLOYEE_BY_ID: "delete-employee-by-id",
};
const development = {
  API_URL_GET_ALL_EMPLOYEES: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_ALL_EMPLOYEES}`,
  API_URL_GET_EMPLOYEE_BY_ID: `${API_BASE_URL_DEV}/${ENDPOINTS.GET_EMPLOYEE_BY_ID}`,
  API_URL_CREATE_EMPLOYEE: `${API_BASE_URL_DEV}/${ENDPOINTS.CREATE_EMPLOYEE}`,
  API_URL_UPDATE_EMPLOYEE: `${API_BASE_URL_DEV}/${ENDPOINTS.UPDATE_EMPLOYEE}`,
  API_URL_DELETE_EMPLOYEE_BY_ID: `${API_BASE_URL_DEV}/${ENDPOINTS.DELETE_EMPLOYEE_BY_ID}`,
};
const production = {
  API_URL_GET_ALL_EMPLOYEES: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_ALL_EMPLOYEES}`,
  API_URL_GET_EMPLOYEE_BY_ID: `${API_BASE_URL_PROD}/${ENDPOINTS.GET_EMPLOYEE_BY_ID}`,
  API_URL_CREATE_EMPLOYEE: `${API_BASE_URL_PROD}/${ENDPOINTS.CREATE_EMPLOYEE}`,
  API_URL_UPDATE_EMPLOYEE: `${API_BASE_URL_PROD}/${ENDPOINTS.UPDATE_EMPLOYEE}`,
  API_URL_DELETE_EMPLOYEE_BY_ID: `${API_BASE_URL_PROD}/${ENDPOINTS.DELETE_EMPLOYEE_BY_ID}`,
};

const Constants =
  process.env.NODE_ENV === "development" ? development : production;
export default Constants;
